
// NODEJS  hocce javascript runtime emvironment manea javascript ke run korar jayga..r ei node js er ekta special framework hocce NESTJS.NODEJS er r ek framwork hocce express but sheita UNOPINIONTED mane kuno strick structure follow korena but NESTJS moduler pattern architecture follow kore.eta fixed..moduler pattern follow kortei hobe.

// package.json file a application er shob dependency gula thake .applcationer main introduction ta thake  but package-log.json file a shei dependecy gular bistarito thake.